[package]
name = "our_fractal_ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
our_fractal_core = { git = "https://github.com/katapy/our_fractal_core.git" }
